apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: flask-k8s-dr
  namespace: ms-prod
spec:
  host: flask-k8s
  subsets:
  - name: prod
    labels:
      version: "1.1"
  - name: canary
    labels:
      version: "1.2"