apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s
spec:
  template:
    spec:
      containers:
        - name: flask-k8s
          env:
            - name: SERVICE_NAME
              value: flask-k8s
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            #httpGet:
            #  path: /
            tcpSocket:
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            #httpGet:
            #  path: /
            tcpSocket:
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5

