apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-k8s-filebeat
  namespace: ms-dev
data:
  filebeat.yml: |-
    filebeat.prospectors:
    - type: log
      paths:
        - /opt/microservices/logs/*.log
      fields:
        env:  dev
        type: python
        service: flask-admin
      fields_under_root: true
      multiline:
        pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}"
        negate: true
        match: after
    output.logstash:
      hosts: ['logstash-svc.elk:5044']