apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flask-k8s-vs
spec:
  hosts:
  - flask-k8s
  http:
  - route:
    - destination:
        host: flask-k8s
        subset: v1
    # 跨域配置
    corsPolicy:
      allowOrigin:
      - '*'
      allowMethods:
      - GET
      - POST 
      - OPTIONS 
      # - PATCH 
      - DELETE
      allowHeaders:
      - 'cluster_name'
      - 'namespace'
