apiVersion: v1
kind: Service
metadata:
  name: flask-k8s
  labels:
    app: flask-k8s
    service: flask-k8s
spec:
  type: NodePort
  ports:
  - port: 8082
    name: http
  selector:
    app: flask-k8s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-k8s-sa
  labels:
    account: flask-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s
  labels:
    app: flask-k8s
spec:
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      #更新时允许最大激增的容器数
      maxSurge: 1
      #更新时允许最大unavailable的容器数
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: flask-k8s 
  template:
    metadata:
      labels:
        app: flask-k8s
    spec:
      serviceAccountName: flask-k8s-sa
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - flask-k8s
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      imagePullSecrets: 
      - name: harborsecret 
      containers:
      - name: flask-k8s
        image: myhub.mydocker.com/ms-dev/flask-k8s:ef9daf2
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: log
          mountPath: /opt/microservices/logs
          # subPath: logs/ms-dev/flask-k8s
        - name: file-config
          mountPath: /opt/microservices/instance
      #log sidecar 
      - name: filebeat
        # image: docker.elastic.co/beats/filebeat:6.7.0
        image: myhub.mydocker.com/elk/filebeat:6.7.0
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        # 挂载filebeat.yml(在configmap中)
        - name: filebeat-config
          mountPath: /etc/filebeat.yml
          subPath: filebeat.yml
        - name: log
          mountPath: /opt/microservices/logs
      volumes:
      # - name: log
      #   persistentVolumeClaim:
      #     claimName: flask-k8s-pvc
      - name: log
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: flask-k8s-filebeat
      - name: file-config
        configMap:
          name: flask-k8s-configmap
