apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-k8s-pvc
  namespace: ms-dev
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  #不要使用默认的sc,手动创建的PV
  storageClassName: ""
