apiVersion: "v1"
kind: "Pod"
metadata:
  name: "jnlp-slave"
  namespace: kube-ops
  labels:
    name: "jnlp-slave"
spec:
  imagePullSecrets:
  - name: harborsecret 
  hostAliases:
  - hostnames:
    - myhub.mydocker.com
    ip: 192.168.11.31
  containers:
  - name: "jnlp-slave"
    image: "myhub.mydocker.com/cnych/jenkins:jnlp7"
    imagePullPolicy: "Always"
    workingDir: "/home/jenkins/agent"
    env:
      - name: "JENKINS_URL"
        value: "http://jenkins.kube-ops.svc.cluster.local:8080/"
    tty: true
    volumeMounts:
    - name: docker
      mountPath: /usr/bin/docker
    - name: "docker-sock"
      mountPath: "/var/run/docker.sock"
      readOnly: false
    - name: "harbor-ssl"
      mountPath: "/etc/harbor/ssl/"
    - name: "ca-bundle-crt"
      mountPath: "/etc/pki/tls/certs/ca-bundle.crt"
    # - name: "k8s-config"
    #   mountPath: "/root/.kube"
    #   readOnly: false
    - name: "workspace-volume"
      mountPath: "/home/jenkins/agent"
      readOnly: false
  serviceAccount: "jenkins"
  volumes:
  - name: docker
    hostPath:
      path: /usr/bin/docker
  - name: "docker-sock"
    hostPath:
      path: "/var/run/docker.sock"
  - name: "harbor-ssl"
    hostPath:
      path: "/etc/harbor/ssl/"
  - name: "ca-bundle-crt"
    hostPath:
      path: "/etc/pki/tls/certs/ca-bundle.crt"
  # - name: "k8s-config"
  #   hostPath:
  #     path: "/root/.kube"
  - name: "workspace-volume"
    emptyDir: {}