apiVersion: v1
kind: ConfigMap
metadata:
  name: $service-configmap
data:
  config.py: |
    import  os
    from redis import Redis

    DEBUG = True
    SECRET_KEY = os.urandom(24)
    SESSION_TYPE = 'redis'
    SESSION_REDIS =  Redis(host='192.168.11.200',port=6689)
    SESSION_USE_SIGNER = True
    # SECRET_KEY = b'_5#y2L"F4Q8z\n\xec]/'
    SESSION_PERMANENT = False
    PERMANENT_SESSION_LIFETIME = 300

    DIALECT = 'mysql'
    DRIVER = 'pymysql'
    USERNAME = 'dev_user'
    PASSWORD = 'abc123456'
    HOST = '192.168.11.200'
    PORT = '52100'
    DATABASE = 'test'

    SQLALCHEMY_DATABASE_URI ="mysql+pymysql://dev_user:abc123456@192.168.11.200:52100/flask-tutorial?charset=utf8"
    # SQLALCHEMY_DATABASE_URI = '{}+{}://{}:{}@{}:{}/{}?charset=utf8'.format(
    #     DIALECT,DRIVER,USERNAME,PASSWORD,HOST,PORT,DATABASE
    # )
    SQLALCHEMY_COMMIT_ON_TEARDOWN = True
    SQLALCHEMY_TRACK_MODIFICATIONS = True

    SQLALCHEMY_POOL_SIZE = 100
    SQLALCHEMY_MAX_OVERFLOW = 30


    SQLALCHEMY_POOL_RECYCLE = 10
