apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flask-k8s-vs
  namespace: ms-prod
spec:
  hosts:
  - flask-k8s
  http:
  - route:
    - destination:
        host: flask-k8s
        subset: prod
      weight: 100
    - destination:
        host: lask-k8s
        subset: canary
      weight: 0
