apiVersion: v1
kind: Service
metadata:
  name: flask-k8s
  namespace: ms-prod
  labels:
    app: flask-k8s
    service: flask-k8s
spec:
  type: NodePort
  ports:
  - port: 8082
    name: http
  selector:
    app: flask-k8s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-prod-flask-k8s
  namespace: ms-prod
  labels:
    account: flask-k8s